name: Testing Failure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs: 
  failski: 
    runs-on: ubuntu-20.04
    
    steps: 
    - name: succeed
      run: docker run python:3.8.3-slim-buster echo $PATH
#    - name: fail
#      run: docker run -v $(pwd):/home python:3.8.3-slim-buster /bin/bash -c "python home/app/request.py"
    - name: fail
      run: |
        docker build -t pythonfail -f Dockerfile2
        docker run pythonfail
