name: Testing Failure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs: 
  failski: 
    runs-on: ubuntu-20.04
    
    steps: 
    - name: succeed
      run: docker run debian:buster-slim echo 1
    - name: fail
      run: docker run -v $(pwd):/ debian:buster-slim python app/request.py
