name: Testing Failure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs: 
  failski: 
    runs-on: ubuntu-20.04
    
    steps: 
    - uses: actions/checkout@v2
    - name: succeed
      run: docker run python:3.8.3-slim-buster echo $PATH
    - name: fail
      run: docker run -v $(pwd):/home python:3.8.3-slim-buster python home/app/request.py
    - name: fail2
      run: |
        docker build -t pythonfail .
        docker run pythonfail
