name: Testing Failure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs: 
  failski: 
    runs-on: ubuntu-20.04
    
    steps: 
    - name: succeed
      run: docker run python:buster-slim echo $PATH
    - name: fail
      run: docker run -v $(pwd):/home python:buster-slim /bin/bash -c "python app/request.py"
