name: When Tagging

on: 
  push:
    tags:
      - "fooski*"
   

jobs:
  echoing: 
    runs-on: ubuntu-latest
    steps: 
      - name: echoing with tag name
        run: |
          echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
          echo The tag was ${{ env.RELEASE_VERSION }}
      - name: did the tag env var persist?
        run: echo The tag was ${{ env.RELEASE_VERSION }}
